Repository cal-itp/mobility-marketplace, pull requests merged in 2020-09, with the labels that each got.

#12 Content management
  _config.yml
  _layouts/category.html
  admin/config.yml
  admin/index.html
  admin/widgets/index.js
  admin/widgets/shortid.js
  content/_actions/agencies.md
  content/_actions/email-signup.md
  content/_actions/epay.md
  content/_categories/eligibility-verification.md
  content/_categories/payment-services.md
  content/_categories/payment-validators.md
  content/_categories/payments.md
  content/index.md
  index.html
Labels: admin

#13 Rendering the Homepage
  _data/nav_footer.yml
  _data/nav_main.yml
  _includes/action-tile.html
  _includes/action-tiles.html
  _includes/feature-card.html
  _includes/feature-cards.html
  _includes/hero.html
  _layouts/default.html
  _layouts/home.html
  _sass/actions.scss
  _sass/default.scss
  _sass/features.scss
  _sass/hero.scss
  _sass/main.scss
  _sass/nav.scss
  _sass/site.scss
  _sass/variables.scss
  admin/config.yml
  content/_actions/agencies.md
  content/_actions/email-signup.md
  content/_actions/epay.md
  content/_categories/eligibility-verification.md
  content/_categories/payment-services.md
  content/_categories/payment-validators.md
  content/index.md
Labels: front-end

#19 Implement blog capability and render posts
  _config.yml
  _data/authors.yml
  _includes/components/author.html
  _includes/components/date-badge.html
  _includes/scripts/moment.html
  _layouts/post.html
  _sass/components.scss
  _sass/content.scss
  _sass/main.scss
  admin/config.yml
  admin/editor/image-caption.js
  admin/editor/index.js
  admin/editor/pull-quote.js
  admin/editor/youtube.js
  admin/index.html
  content/_posts/2020-09-03-payments-101.md
Labels: admin, front-end

#23 Rendering Categories pages
  _includes/components/action-button.html
  _includes/components/action-tile.html
  _includes/components/article-card.html
  _includes/components/card-grid.html
  _includes/components/date-badge.html
  _includes/components/feature-card.html
  _includes/components/feature-cards.html
  _layouts/category.html
  _layouts/home.html
  _sass/category.scss
  _sass/components.scss
  _sass/content.scss
  _sass/main.scss
  _sass/post.scss
  _sass/site.scss
  _sass/variables.scss
  admin/config.yml
  content/_actions/email-signup.md
  content/_actions/epay.md
  content/_categories/eligibility-verification.md
  content/_categories/open-loop-payments.md
  content/_categories/payment-acceptance.md
  content/_categories/payment-services.md
  content/_categories/payment-validators.md
  content/_posts/2020-06-01-epay-illustrated-guide-for-all-transit-agencies.md
  content/_posts/2020-07-14-buying-transit-like-coffee.md
  content/_posts/2020-08-08-payments-101.md
  content/_posts/2020-08-20-epay-signup-instructions.md
  content/index.md
Labels: front-end

#25 Visual refresh
  _data/nav_main.yml
  _includes/components/action-button.html
  _includes/components/action-tile.html
  _includes/components/action-tiles.html
  _includes/components/card-grid.html
  _includes/components/cards/action-tile.html
  _includes/components/cards/action.html
  _includes/components/cards/article.html
  _includes/components/cards/category-image.html
  _includes/components/cards/grid.html
  _includes/components/feature-card.html
  _includes/components/hero.html
  _includes/site/head.html
  _includes/site/header.html
  _includes/site/navigation.html
  _layouts/category.html
  _layouts/home.html
  _layouts/post.html
  _sass/components.scss
  _sass/components/cards.scss
  _sass/components/date-badge.scss
  _sass/components/hero.scss
  _sass/main.scss
  _sass/mixins.scss
  _sass/navigation.scss
  _sass/pages/category.scss
  _sass/pages/home.scss
  _sass/pages/post.scss
  _sass/site.scss
  _sass/variables.scss
  admin/config.yml
  assets/images/logo-lg.svg
  assets/images/logo-sm.svg
  content/_actions/agencies.md
  content/_actions/email-signup.md
  content/_actions/epay.md
  content/_categories/eligibility-verification.md
  content/_categories/open-loop-payments.md
  content/_categories/payment-acceptance.md
  content/index.md
  favicon.ico
Labels: front-end

#26 Deploying homepage visual refresh
  README.md
  _config.yml
  _data/nav_main.yml
  _includes/components/action-button.html
  _includes/components/action-tile.html
  _includes/components/action-tiles.html
  _includes/components/card-grid.html
  _includes/components/cards/action-tile.html
  _includes/components/cards/action.html
  _includes/components/cards/article.html
  _includes/components/cards/category-image.html
  _includes/components/cards/grid.html
  _includes/components/feature-card.html
  _includes/components/hero.html
  _includes/site/head.html
  _includes/site/header.html
  _includes/site/navigation.html
  _layouts/category.html
  _layouts/home.html
  _layouts/post.html
  _sass/components.scss
  _sass/components/cards.scss
  _sass/components/date-badge.scss
  _sass/components/hero.scss
  _sass/main.scss
  _sass/mixins.scss
  _sass/navigation.scss
  _sass/pages/category.scss
  _sass/pages/home.scss
  _sass/pages/post.scss
  _sass/site.scss
  _sass/variables.scss
  admin/config.yml
  admin/plugins/ca-state-fonts/package.json
  assets/images/logo-lg.svg
  assets/images/logo-sm.svg
  content/_actions/agencies.md
  content/_actions/email-signup.md
  content/_actions/epay.md
  content/_categories/eligibility-verification.md
  content/_categories/open-loop-payments.md
  content/_categories/payment-acceptance.md
  content/index.md
  docker-compose.yml
  favicon.ico
Labels: front-end

#27 Add Google Analytics
  _config.yml
  _includes/scripts/ga.html
  _includes/site/head.html
  netlify.toml
Labels: admin

#22 Map prototype
  _includes/scripts/mapbox.html
  _includes/scripts/script.html
  _includes/scripts/tag.html
  _sass/main.scss
  _sass/pages/providers.scss
  content/_actions/providers.md
  content/providers.html
  scripts/map.js
Labels: front-end

#30 Releasing initial work on Provider map
  _includes/scripts/mapbox.html
  _includes/scripts/script.html
  _includes/scripts/tag.html
  _sass/main.scss
  _sass/pages/providers.scss
  content/_actions/providers.md
  content/providers.html
  data/counties.geojson
  data/glossary.md
  data/providers.csv
  scripts/map.js
Labels: front-end, release

#31 Removing homepage category tiles
  _includes/components/hero.html
  _includes/components/hero/tile.html
  _includes/components/mobile-tile.html
  _layouts/bg-white.html
  _layouts/home.html
  _sass/components/hero.scss
  _sass/components/mobile-tile.scss
  _sass/main.scss
  _sass/pages/home.scss
  admin/config.yml
  content/index.md
Labels: CMS, front-end

#32 Email signup form
  _data/nav_footer.yml
  _data/nav_main.yml
  _includes/forms/general.html
  _includes/forms/indicates-required.html
  _includes/forms/indicator.html
  _layouts/form.html
  _sass/components/cards.scss
  _sass/content.scss
  _sass/forms.scss
  _sass/main.scss
  _sass/pages/form.scss
  _sass/variables.scss
  admin/config.yml
  content/_actions/subscribe.md
  content/pages/index.md
  content/pages/providers.html
  content/pages/subscribe.md
Labels: admin, front-end

#34 Light SEO work
  _config.yml
  _includes/scripts/jquery.html
  _includes/site/favicon.html
  _includes/site/fonts.html
  _includes/site/head.html
  _includes/site/meta/base.html
  _includes/site/meta/description.html
  _includes/site/meta/og-image.html
  _includes/site/meta/title.html
  _includes/site/meta/url.html
  _includes/site/styles.html
  assets/images/favicon.ico
  robots.txt
Labels: admin

#36 Form submission confirmation
  _includes/forms/subscribe.html
  _sass/forms.scss
  admin/config.yml
  content/_actions/return-home.md
  content/pages/subscribe.md
  scripts/forms/subscribe.js
Labels: CMS, front-end

#40 Improved Netlify CMS configuration
  _data/meta.yml
  _includes/components/cards/action-tile.html
  _includes/components/cards/action.html
  _includes/components/cards/category-image.html
  _includes/components/hero.html
  _includes/scripts/netlify-identity.html
  _includes/site/meta/description.html
  _includes/site/meta/og-image.html
  _includes/site/meta/title.html
  _includes/site/navigation.html
  _layouts/category.html
  _layouts/home.html
  admin/config.yml
  admin/index.html
  admin/login.js
  assets/uploads/card-providers-map.png
  content/_actions/epay.md
  content/_actions/providers.md
  content/_actions/subscribe.md
  content/_categories/eligibility-verification.md
  content/_categories/open-loop-payments.md
  content/_categories/payment-acceptance.md
  content/pages/index.md
Labels: CMS

#42 Pushing CMS configuration changes
  _data/meta.yml
  _includes/components/cards/action-tile.html
  _includes/components/cards/action.html
  _includes/components/cards/category-image.html
  _includes/components/hero.html
  _includes/scripts/netlify-identity.html
  _includes/site/meta/description.html
  _includes/site/meta/og-image.html
  _includes/site/meta/title.html
  _includes/site/navigation.html
  _layouts/category.html
  _layouts/home.html
  admin/config.yml
  admin/index.html
  admin/login.js
  assets/uploads/card-providers-map.png
  content/_actions/epay.md
  content/_actions/providers.md
  content/_actions/subscribe.md
  content/_categories/eligibility-verification.md
  content/_categories/open-loop-payments.md
  content/_categories/payment-acceptance.md
  content/pages/index.md
Labels: release

#43 Update Call to Action “providers”
  content/_actions/providers.md
Labels: netlify-cms/pending_publish

#44 Update Pages “homepage”
  content/pages/index.md
Labels: netlify-cms/pending_publish

#45 Update Pages “subscribe”
  content/pages/subscribe.md
Labels: netlify-cms/pending_publish

#46 Update Call to Action “subscribe”
  content/_actions/subscribe.md
Labels: netlify-cms/pending_publish

#47 Update Pages “providers”
  content/pages/providers.md
Labels: netlify-cms/pending_publish

#48 Update Pages “glossary”
  _data/glossary.yml
Labels: netlify-cms/pending_publish

#50 Fix Providers table sort
  scripts/providers/table.js
Labels: bug, front-end

#52 Remove old leftover file
  content/pages/providers.html
Labels: bug, data, release

#55 provider list bug fixes
  data/providers/providers.csv
Labels: data

#56 Update Pages “homepage”
  content/pages/index.md
Labels: netlify-cms/pending_publish

#53 Update counties.geojson
  data/providers/counties.geojson
Labels: data

#57 Releasing fixes for the Providers data
  data/providers/counties.geojson
  data/providers/dictionary.csv
  data/providers/providers.csv
Labels: data, release

#58 Update dictionary.csv
  data/providers/dictionary.csv
Labels: data

#60 Homepage updates
  _includes/components/cards/action-panel.html
  _includes/components/hero.html
  _includes/components/mobile-hero-tile.html
  _includes/components/mobile-tile.html
  _layouts/default.html
  _layouts/home.html
  _sass/components/buttons.scss
  _sass/components/cards.scss
  _sass/components/hero.scss
  _sass/components/mobile-tile.scss
  _sass/content.scss
  _sass/main.scss
  _sass/pages/home.scss
  _sass/variables.scss
  admin/config.yml
  assets/uploads/card-payments.svg
  assets/uploads/card-providers-map.png
  assets/uploads/card-providers-map.svg
  assets/uploads/homepage_hero.png
  assets/uploads/transit-stop-home.svg
  content/_actions/epay.md
  content/_actions/providers.md
  content/_actions/subscribe.md
  content/pages/index.md
Labels: CMS, front-end

#61 Releasing data and homepage updates
  _includes/components/cards/action-panel.html
  _includes/components/hero.html
  _includes/components/mobile-hero-tile.html
  _includes/components/mobile-tile.html
  _layouts/default.html
  _layouts/home.html
  _sass/components/buttons.scss
  _sass/components/cards.scss
  _sass/components/hero.scss
  _sass/components/mobile-tile.scss
  _sass/content.scss
  _sass/main.scss
  _sass/pages/home.scss
  _sass/variables.scss
  admin/config.yml
  assets/uploads/card-payments.svg
  assets/uploads/card-providers-map.png
  assets/uploads/card-providers-map.svg
  assets/uploads/homepage_hero.png
  assets/uploads/transit-stop-home.svg
  content/_actions/epay.md
  content/_actions/providers.md
  content/_actions/subscribe.md
  content/pages/index.md
  data/providers/dictionary.csv
Labels: release

#77 Display content in hero actions
  _includes/components/actions/button.html
  _includes/components/actions/content.html
  _includes/components/actions/hero.html
  _includes/components/cards/action-panel.html
  _includes/components/hero.html
  _includes/components/mobile-hero-tile.html
  _includes/forms/subscribe.html
  _layouts/category.html
  _layouts/providers.html
  _sass/components/hero.scss
  content/pages/index.md
Labels: front-end

#78 Hero action update
  _includes/components/actions/button.html
  _includes/components/actions/content.html
  _includes/components/actions/hero.html
  _includes/components/cards/action-panel.html
  _includes/components/hero.html
  _includes/components/mobile-hero-tile.html
  _includes/forms/subscribe.html
  _layouts/category.html
  _layouts/providers.html
  _sass/components/hero.scss
  content/pages/index.md
Labels: release
