Repository cal-itp/mobility-marketplace, pull requests merged in 2022-10, with the labels that each got.

#369 Feat: add link to existing data plan contracts
  src/_data/contracts.yml
  src/contracts/index.html
  src/uploads/connectivity.svg
Labels: content

#379 docs(README): add server address to instructions
  README.md
Labels: documentation

#380 chore(gitignore): ignore all .DS_Store files from Mac users
  .gitignore
Labels: chore
